version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_nest
      MYSQL_USER: facuar
      MYSQL_PASSWORD: supersecretpassword
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3307:3306'
